services:
  db: 
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/data/db:/var/lib/mysql
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports: 
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - bundle_cache:/user/local/bundle
    depends_on:
      - db

volumes:
  bundle_cache:
